import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Classic Linen Shirt',
    description: 'A timeless classic, this linen shirt is perfect for any occasion. Made from 100% pure linen for a comfortable and breathable fit.',
    price: 75.0,
    images: ['https://placehold.co/600x800', 'https://placehold.co/600x800', 'https://placehold.co/600x800'],
    sizes: ['S', 'M', 'L'],
    category: 'Men',
    dataAiHint: 'male model',
  },
  {
    id: '2',
    name: 'Elegant Silk Blouse',
    description: 'Add a touch of elegance to your wardrobe with this beautiful silk blouse. Features a delicate tie-neck and soft, flowing fabric.',
    price: 120.0,
    images: ['https://placehold.co/600x800', 'https://placehold.co/600x800'],
    sizes: ['XS', 'S', 'M'],
    category: 'Women',
    dataAiHint: 'female fashion',
  },
  {
    id: '3',
    name: 'Urban Explorer Jacket',
    description: 'Stay stylish and warm with the Urban Explorer jacket. Water-resistant and designed for the modern adventurer.',
    price: 195.0,
    images: ['https://placehold.co/600x800'],
    sizes: ['M', 'L', 'XL'],
    category: 'New Arrivals',
    dataAiHint: 'urban fashion',
  },
  {
    id: '4',
    name: 'Tailored Chino Trousers',
    description: 'Our best-selling chinos are a wardrobe staple. Perfectly tailored for a smart, comfortable fit that lasts all day.',
    price: 90.0,
    images: ['https://placehold.co/600x800', 'https://placehold.co/600x800'],
    sizes: ['S', 'M', 'L', 'XL'],
    category: 'Best Sellers',
    dataAiHint: 'mens trousers',
  },
  {
    id: '5',
    name: 'Flowy Maxi Dress',
    description: 'A stunning maxi dress with a floral print, perfect for sunny days and special events. Lightweight and effortlessly chic.',
    price: 150.0,
    images: ['https://placehold.co/600x800', 'https://placehold.co/600x800'],
    sizes: ['S', 'M', 'L'],
    category: 'Women',
    dataAiHint: 'summer dress',
  },
  {
    id: '6',
    name: 'Essential Crewneck Tee',
    description: 'The perfect t-shirt, made from premium soft cotton. A must-have for every wardrobe, available in multiple colors.',
    price: 45.0,
    images: ['https://placehold.co/600x800'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    category: 'Best Sellers',
    dataAiHint: 'basic tshirt',
  },
  {
    id: '7',
    name: 'Modern Knit Sweater',
    description: 'A cozy and stylish knit sweater, featuring a contemporary design and a soft wool blend. Ideal for cooler weather.',
    price: 110.0,
    images: ['https://placehold.co/600x800', 'https://placehold.co/600x800'],
    sizes: ['S', 'M', 'L'],
    category: 'Men',
    dataAiHint: 'mens sweater',
  },
  {
    id: '8',
    name: 'High-Waisted Skinny Jeans',
    description: 'Flatter your figure with our top-rated high-waisted skinny jeans. Made with stretch denim for ultimate comfort and style.',
    price: 95.0,
    images: ['https://placehold.co/600x800', 'https://placehold.co/600x800'],
    sizes: ['XS', 'S', 'M'],
    category: 'Women',
    dataAiHint: 'womens jeans',
  },
  {
    id: '9',
    name: 'Avant-Garde Trench Coat',
    description: 'Make a statement with this new avant-garde trench coat. A modern take on a classic piece, with bold lines and a unique silhouette.',
    price: 250.0,
    images: ['https://placehold.co/600x800'],
    sizes: ['M', 'L'],
    category: 'New Arrivals',
    dataAiHint: 'fashion coat',
  },
  {
    id: '10',
    name: 'Performance Polo Shirt',
    description: 'Engineered for comfort and performance, this polo shirt features moisture-wicking fabric and a sleek, athletic fit.',
    price: 65.0,
    images: ['https://placehold.co/600x800', 'https://placehold.co/600x800'],
    sizes: ['S', 'M', 'L', 'XL'],
    category: 'Men',
    dataAiHint: 'polo shirt',
  },
  {
    id: '11',
    name: 'Cashmere Scarf',
    description: 'Wrap yourself in luxury with our best-selling 100% cashmere scarf. Incredibly soft and warm, the perfect accessory.',
    price: 130.0,
    images: ['https://placehold.co/600x800'],
    sizes: ['L'],
    category: 'Best Sellers',
    dataAiHint: 'cashmere scarf',
  },
  {
    id: '12',
    name: 'Pleated A-Line Skirt',
    description: 'A chic and versatile A-line skirt with crisp pleats. Dress it up or down for any occasion.',
    price: 85.0,
    images: ['https://placehold.co/600x800', 'https://placehold.co/600x800'],
    sizes: ['XS', 'S', 'M'],
    category: 'Women',
    dataAiHint: 'fashion skirt',
  },
];
